### PR TITLE
Add smoke test for all challenges

### LINKED ISSUE #49: Add smoke tests for all challenges
With #47 we have introduced a smoke test script that allows to quickly check for issues. However, we have intentionally excluded the following challgenges from the test as they rely on other challenges being run:

* frozen-querying
* combined-indexing-and-querying
* elasticlogs-querying

When elastic/rally#697 is implemented we can change the smoke test script so it allows us to spin up a cluster and run multiple challenges against it which allows us to also test the challenges above.

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we leverage new functionality in Rally to spin up a
cluster before all challenges are executed. This allows us to run
challenges which depend on others (e.g. query only challenges that rely
on another challenge to actually put the data into the cluster).

Closes #49

### CODE REVIEW

**Comment by ebadyano** [comment]
It must be something weird with my setup, but I get this error when I ran `smoke-test.sh`:
```
13:47 $ ./smoke-test.sh
pyenv: esrally: command not found

The `esrally' command exists in these Python versions:
  3.7.0
```

**Comment by danielmitterdorfer** [comment]
> It must be something weird with my setup [...]

@ebadyano I've added a new makefile target in https://github.com/elastic/rally-eventdata-track/pull/61/commits/eedadbbfcf69e612273fa51573486390efaf6da6 to simplify local testing.

Can you please do the following?

```
make install
make it
```

The latter target will run the smoke tests with Rally properly setup (i.e. from now on, executing `smoke-test.sh` directly is discouraged).

**Comment by ebadyano** [comment]
I tried again and after make install, make it gives the following:
```
✔ ~/rally-eventdata-track [complete-smoke-test|…2]
12:16 $ make it
. .venv/bin/activate; ./smoke-test.sh
[2019-12-16T17:16:59Z] [INFO] preparing cluster

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/


--------------------------------
[INFO] SUCCESS (took 10 seconds)
--------------------------------
**************************************** TESTING LIST TRACKS *******************************************

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[ERROR] Cannot list. Expected a git repository at [/Users/ebadyano/.rally/benchmarks/tracks/eventdata] but the directory does not exist.

Getting further help:
*********************
* Check the log files in /Users/ebadyano/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/latest/
* Ask a question on the forum at https://discuss.elastic.co/c/elasticsearch/rally
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /Users/ebadyano/.rally/logs.

-------------------------------
[INFO] FAILURE (took 0 seconds)
-------------------------------
[2019-12-16T17:17:14Z] [INFO] tearing down

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/


-------------------------------
[INFO] SUCCESS (took 0 seconds)
-------------------------------
make: *** [it] Error 64
```

**Comment by danielmitterdorfer** [comment]
@ebadyano now, this is odd and unexpected. Please ping me directly when you are available and we'll get this sorted out.

**Comment by ebadyano** [comment]
the test works for me now! Thank you!

**Comment by danielmitterdorfer** [comment]
Thanks for the review! :)

**Pull request merged**
